import { createHash } from 'node:crypto'
import { defineConfig } from 'vite'
import type { Plugin } from 'vite'
import react from '@vitejs/plugin-react'

/**
 * Files the shell needs offline that are not part of the JS bundle graph.
 *
 * `index.html` is listed explicitly: it is emitted after this hook runs, so it
 * never appears in `bundle` and would otherwise be missing from the precache —
 * which is exactly the file a reload with no signal depends on.
 */
const STATIC_ASSETS = [
  './index.html',
  './manifest.webmanifest',
  './icon-192.png',
  './icon-512.png',
  './icon-maskable-512.png',
  './apple-touch-icon.png',
]

/**
 * Emits a service worker that precaches this exact build.
 *
 * Written by hand rather than pulled from Workbox: the whole precache list is
 * a dozen files, and a learner standing in a commune health station with no
 * signal deserves a cache strategy someone can actually read. The cache name
 * is derived from the built filenames, so every build gets a fresh cache and
 * old ones are dropped on activate.
 */
function serviceWorker(): Plugin {
  return {
    name: 'clerkmate-service-worker',
    apply: 'build',
    generateBundle(_options, bundle) {
      const emitted = Object.keys(bundle).map((file) => `./${file}`)
      const precache = [...new Set(['./', './index.html', ...emitted, ...STATIC_ASSETS])]
      const version = createHash('sha256').update(precache.join('|')).digest('hex').slice(0, 10)

      const source = `/* Generated by vite.config.ts — do not edit. */
const CACHE = 'clerkmate-${version}'
const PRECACHE = ${JSON.stringify(precache, null, 2)}

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)))
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  )
})

// The page asks for the update; the worker never takes over mid-session on its
// own, because swapping the app out from under someone mid-note is hostile.
self.addEventListener('message', (event) => {
  if (event.data === 'SKIP_WAITING') self.skipWaiting()
})

self.addEventListener('fetch', (event) => {
  const request = event.request
  if (request.method !== 'GET') return
  const url = new URL(request.url)
  if (url.origin !== self.location.origin) return

  // Navigations always resolve to the cached shell, so a reload with no signal
  // still opens the app. The records themselves live in IndexedDB, untouched.
  if (request.mode === 'navigate') {
    event.respondWith(
      caches
        .match('./index.html')
        .then((cached) => cached || caches.match('./'))
        .then((cached) => cached || fetch(request)),
    )
    return
  }

  event.respondWith(
    caches.match(request).then((cached) => {
      if (cached) return cached
      return fetch(request).then((response) => {
        if (response.ok && response.type === 'basic') {
          const copy = response.clone()
          caches.open(CACHE).then((cache) => cache.put(request, copy))
        }
        return response
      })
    }),
  )
})
`
      this.emitFile({ type: 'asset', fileName: 'sw.js', source })
    },
  }
}

export default defineConfig({
  plugins: [react(), serviceWorker()],
  base: './',
  server: { host: true, port: 5173 },
  build: { target: 'es2020', outDir: 'dist' },
})
